language: perl
perl:
    - "5.22"
    - "5.26"
    - "5.30"
addons:
    apt:
        packages:
            - texlive
            - texlive-latex-extra
            - texlive-lang-european
install:
    - "cpanm --quiet --notest --installdeps ."
script: "prove -v test"
