language: perl
perl:
    - "5.12"
    - "5.22"
    - "5.24"
addons:
    apt:
        packages:
            - texlive
            - texlive-latex-extra
install:
    - "cpanm --quiet --notest --installdeps ."
script: "prove -v test"
