language: perl
perl:
    - "5.12"
    - "5.22"
    - "5.24"
addons:
    apt:
        packages:
            - texlive
            - texlive-latex-extra
install:
    - "cpanm --quiet --notest Data::Dumper File::Slurp Getopt::Long JSON::XS Makefile::Parser PDF::API2::Util PDF::Reuse Text::vCard Text::vCard::Addressbook"
script: "prove -v test"
